services:
  mmdetection:
    build:
      context: ./mmdetection
    container_name: mmdetection
    ports:
      - "8000:8000" 
    networks:
      - my_network
    environment:
      - CUDA_VISIBLE_DEVICES=all
    
  cascadetabnet:
    build:
      context: ./CascadeTabNet
    container_name: cascadetabnet
    depends_on:
      - mmdetection
    ports:
      - "6006:6006"
    networks:
      - my_network
    environment:
      - CUDA_VISIBLE_DEVICES=all

networks:
  my_network:
    driver: bridge
